image:
  repo: crapps.azurecr.io

probes:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/client_max_body_size: 10m
    nginx.ingress.kubernetes.io/proxy-body-size: 10m

  tlsSecret: "ep-connect-admin-users-svc-cert"
  applicationPath: "/services/users"

